name: Pedro Vieira
description: Software Craftsman Apprentice
meta_description: "Pedro Vieira, Software Craftsman Apprentice"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://pvieira91.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://pvieira91.github.io'
author:         'Pedro Vieira'
